swagger: "2.0"
info:
  description: A simple "Hello World" function
  title: hello-world
  version: "1.0"
  x-direktiv-meta:
    container: gcr.io/direktiv/apps/hello-world
    maintainer: |-
      [direktiv.io](https://www.direktiv.io) 
    issues: https://github.com/direktiv-apps/hello-world/issues
    url: https://github.com/direktiv-apps/hello-world  
    categories:
    - unspecified
    license: |-
      [Apache-2.0](https://www.apache.org/licenses/LICENSE-2.0)
    long-description: >-
      Greet yourself with this function.
consumes:
- application/json
produces:
- application/json
schemes:
- http
paths:
  /: 
    delete:
      parameters:
        - name: Direktiv-ActionID
          in: header
          type: string
          description: |
            On cancel Direktiv sends a DELETE request to
            the action with id in the header
      x-direktiv:
        cancel: echo 'cancel {{ .DirektivActionID }}'
      responses:
        200:
    post:
      parameters:
        - name: Direktiv-ActionID
          in: header
          type: string
          default: development
          description: |
            direktiv action id is an UUID. 
            For development it can be set to 'development'
        - name: Direktiv-TempDir
          in: header
          type: string
          default: /tmp
          description: |
            direktiv temp dir is the working directory for that request
            For development it can be set to e.g. '/tmp'
        - name: body
          in: body
          schema:
            type: object
            required: ["name"]
            properties:
              name:
                type: string
                default: World

      # direktiv code generation is configured here
      x-direktiv-function: |-
        functions:
        - id: hello-world
          image: gcr.io/direktiv/apps/hello-world:1.0
          type: knative-workflow
      x-direktiv-examples:
        - title: Basic
          content: |-
            - id: hello-world
              type: action
              action:
                function: hello-world
                input: 
                  name: MyName
      x-direktiv: 
        cmds:
        - action: exec
          exec: echo {{ .Name }}
        output: |
          {
            "hello-world": "Hello {{ index (index . 0) "result" }}"
          }
      x-direktiv-errors:
        io.direktiv.command.error: Command execution failed
        io.direktiv.output.error: Template error for output generation of the service
        io.direktiv.ri.error: Can not create information object from request
      responses:
        200:
          description: List of executed commands.
          examples:
            hello-world: Hello MyName
          schema:
            type: object
            properties:
              hello-world:
                type: string
        default:
          description: generic error response
          headers:
            Direktiv-ErrorCode:
              type: string
            Direktiv-ErrorMessage:
              type: string
          schema:
            $ref: "#/definitions/error"
definitions:
  direktivFile:
    type: object
    x-go-type:
      type: DirektivFile
      import:
        package: github.com/direktiv/apps/go/pkg/apps 
  error:
    type: object
    required:
      - errorCode
      - errorMessage
    properties:
      errorCode:
        type: string
      errorMessage:
        type: string
